 
language: android
jdk: oraclejdk8

sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
env:
  global:
    - ANDROID_API_LEVEL=27
      #- EMULATOR_API_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
      #- ANDROID_ABI=armeabi-v7a
      #- ANDROID_TAG=google_apis
      #- ADB_INSTALL_TIMEOUT=20 

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
      #- android-$EMULATOR_API_LEVEL
    - extra
    - extra-google-google_play_services
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-${ANDROID_ABI}-${ANDROID_TAG}-$EMULATOR_API_LEVEL

before_script:
  #- export ANDROID_SDK_ROOT=/usr/local/android-sdk
  #- export QEMU_AUDIO_DRV=none 
  #- echo y | sdkmanager --update
  #- sdkmanager "platform-tools" "platforms;android-${EMULATOR_API_LEVEL}"
  #- echo no | android create avd --force -n test -k "system-images;android-${EMULATOR_API_LEVEL};${ANDROID_TAG};${ANDROID_ABI}" 
  #- /usr/local/android-sdk/emulator/emulator -avd test -no-skin -no-window -engine classic &
  #- android-wait-for-emulator
  #- adb shell input keyevent 82 &



script:
  #- ./gradlew clean check connectedCheck 
  - ./gradlew assemble
