 
language: android
jdk: oraclejdk7

sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
env:
  global:
    - ANDROID_API_LEVEL=27
    - EMULATOR_API_LEVEL=27
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
    - ANDROID_ABI=x86
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    - extra
    - extra-google-google_play_services
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-x86-google_apis-$ANDROID_API_LEVEL

before_script:
  - android list targets
  - ls /usr/local/android-sdk/system-images
  - export ANDROID_SDK_ROOT=/usr/local/android-sdk
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG 
  - emulator -avd test -no-audio -no-window -verbose &
  - android-wait-for-emulator


script:
  - ./gradlew clean check connectedCheck -x library:signArchives -PdisablePreDex
